#! /bin/sh
## Like "rcp" but uses netcat on a high port.
## do "ncp targetfile" on the RECEIVING machine
## do "ncp sourcefile receiverhost" on the SENDING machine

## pick your own personal favorite port, which will be used on both ends.
## You should probably change this for your own uses.
MYPORT=28777

test "$3" && echo "too many args" && exit 1
test ! "$1" && echo "no args?" && exit 1

# if second arg, it's a host to send an extant file to [which must exist]
if test "$2" ; then
  test ! -f "$1" && echo "can't find $1" && exit 1
  nc -v -w 2 -p $MYPORT $2 $MYPORT < "$1" && exit 0
  echo "transfer FAILED!"
  exit 1
fi

# fall here for receiver.  For now, don't trash existing files, just in case
test -f "$1" && echo "$1 already exists -- punting!" && exit 1
# 30 seconds oughta be pleeeeenty of time, but change if you want.
nc -v -w 30 -p $MYPORT -l > "$1" && exit 0
echo "transfer FAILED!"
rm -f "$1"
exit 1
